# Generated by Django 4.2.1 on 2023-10-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labthesis',
            name='batch',
        ),
    ]
