# Generated by Django 3.2.16 on 2023-01-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product'),
    ]

    operations = [
        migrations.RunSQL("""
            /*INSERT INTO catalogue_product (
                id,
                name
            )
            SELECT
                id,
                name
            FROM
                trialapp_product;
            SELECT setval(pg_get_serial_sequence('"catalogue_product"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "catalogue_product";*/
        """, reverse_sql="""
            INSERT INTO trialapp_product (
                id,
                name
            )
            SELECT
                id,
                name
            FROM
                catalogue_product;
        """)
    ]
