# Generated by Django 3.2.16 on 2023-02-18 23:37

import baaswebapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20230119_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
        migrations.CreateModel(
            name='RateUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.batch')),
                ('rate_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.rateunit')),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
        migrations.AddField(
            model_name='batch',
            name='rate_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.rateunit'),
        ),
    ]
