# Generated by Django 3.2.16 on 2023-02-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20230219_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
            preserve_default=False,
        ),
    ]
