# Generated by Django 3.2.16 on 2023-02-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_productvariant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='product',
        ),
        migrations.AddField(
            model_name='batch',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.productvariant'),
            preserve_default=False,
        ),
    ]
