# Generated by Django 3.2.18 on 2023-04-09 14:03

import baaswebapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20230310_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=100)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=100)),
                ('max_temp', models.DecimalField(decimal_places=20, max_digits=100)),
                ('min_temp', models.DecimalField(decimal_places=20, max_digits=100)),
                ('mean_temp', models.DecimalField(decimal_places=20, max_digits=100)),
                ('precipitation', models.DecimalField(decimal_places=20, max_digits=100)),
                ('precipitation_hours', models.DecimalField(decimal_places=20, max_digits=100)),
                ('max_wind_speed', models.DecimalField(decimal_places=20, max_digits=100)),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
    ]
