# Generated by Django 3.2.18 on 2023-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='soil_moist_0_1cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_1_3cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_27_81cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_3_9cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_9_27cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_0cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_18cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_54cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_6cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_wind_speed',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='mean_temp',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
        migrations.AlterField(
            model_name='weather',
            name='precipitation_hours',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
    ]
