# Generated by Django 3.2.18 on 2023-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20230422_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='soil_moist_0_1cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_moist_1_3cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_moist_27_81cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_moist_3_9cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_moist_9_27cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_temp_0cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_temp_18cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_temp_54cm',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='soil_temp_6cm',
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_0_to_7cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_100_to_255cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_28_to_100cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_moist_7_to_28cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_0_to_7cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_100_to_255cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_28_to_100cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_temp_7_to_28cm',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
    ]
