# Generated by Django 3.2.18 on 2023-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20230422_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='recent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
