# Generated by Django 3.2.18 on 2023-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_weather_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='dew_point',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='relative_humidity',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True),
        ),
    ]
