# Generated by Django 3.2.18 on 2023-05-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20230501_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
