# Generated by Django 4.2.1 on 2023-07-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_delete_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_substance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
