# Generated by Django 4.2.1 on 2023-08-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_product_active_sustance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='biological',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('FRT', 'Fertilizer'), ('EST', 'Estimulant'), ('INS', 'Insecticide'), ('NMC', 'Nematicide'), ('FGC', 'Fungicide'), ('HRB', 'Herbicide')], default='UNK', max_length=3),
        ),
    ]
