# Generated by Django 4.2.1 on 2023-08-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_product_biological_product_type_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
