# Generated by Django 4.2.1 on 2023-08-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_remove_product_category_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='key_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
