# Generated by Django 4.2.4 on 2023-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_vendor_key_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pest_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='security_period',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weather_humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weather_temperature',
            field=models.IntegerField(null=True),
        ),
    ]
