# Generated by Django 4.2.4 on 2023-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_product_application_product_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mixes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
