# Generated by Django 4.2.4 on 2023-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
