# Generated by Django 4.2.1 on 2023-10-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_remove_labthesis_batch'),
        ('catalogue', '0024_treatment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
