# Generated by Django 3.2.18 on 2023-05-23 09:25

import baaswebapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaswebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recent', models.BooleanField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=100)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=100)),
                ('max_temp', models.DecimalField(decimal_places=5, max_digits=100)),
                ('min_temp', models.DecimalField(decimal_places=5, max_digits=100)),
                ('mean_temp', models.DecimalField(decimal_places=5, max_digits=100)),
                ('soil_temp_0_to_7cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_temp_7_to_28cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_temp_28_to_100cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_temp_100_to_255cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_moist_0_to_7cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_moist_7_to_28cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_moist_28_to_100cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('soil_moist_100_to_255cm', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('dew_point', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('relative_humidity', models.DecimalField(decimal_places=2, default=None, max_digits=100, null=True)),
                ('precipitation', models.DecimalField(decimal_places=5, max_digits=100)),
                ('precipitation_hours', models.DecimalField(decimal_places=5, max_digits=100)),
                ('max_wind_speed', models.DecimalField(decimal_places=5, max_digits=100)),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
    ]
