# Generated by Django 3.2.18 on 2023-06-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baaswebapp', '0002_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.UUIDField(default=None, null=True)),
                ('person_group_id', models.UUIDField(default=None, null=True)),
                ('accepted_invite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceid_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faceid_data', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
