# Generated by Django 4.2.1 on 2023-09-16 11:35

import baaswebapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaswebapp', '0002_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('UNK', 'Unknown'), ('N_T', 'Create Trial'), ('U_T', 'Update Trial'), ('N_P', 'Create Product'), ('U_P', 'Update Product')], default='UNK', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
    ]
