# Generated by Django 3.2.18 on 2023-06-21 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baaswebapp', '0003_faceiddata_inviteduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedUser',
            new_name='FaceIdUser',
        ),
        migrations.AlterField(
            model_name='faceiddata',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='faceiduser',
            name='faceid_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faceid_data', to='baaswebapp.faceiddata'),
        ),
    ]
