# Generated by Django 3.2.18 on 2023-06-21 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baaswebapp', '0004_auto_20230621_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceiduser',
            name='faceid_data',
        ),
        migrations.AddField(
            model_name='faceiduser',
            name='accepted_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faceiduser',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='faceiduser',
            name='person_group_id',
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='FaceIdData',
        ),
    ]
