# Generated by Django 4.2.1 on 2023-10-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaswebapp', '0005_alter_eventlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('N_T', 'new trial'), ('U_T', 'update trial'), ('D_T', 'delete trial'), ('T_D', 'trial done'), ('N_TH', 'new thesis'), ('U_TH', 'update thesis'), ('D_TH', 'delete thesis'), ('N_ASS', 'new assessment'), ('U_ASS', 'update assessment'), ('D_ASS', 'delete assessment'), ('N_APP', 'new application'), ('U_APP', 'update application'), ('D_APP', 'delete application'), ('N_P', 'new product'), ('U_P', 'update product'), ('D_P', 'delete product'), ('N_TT', 'new TREATMENT'), ('U_TT', 'update TREATMENT'), ('D_TT', 'delete TREATMENT'), ('N_DT', 'new data')], default='UNK', max_length=10),
        ),
    ]
