# Generated by Django 4.2.4 on 2024-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaswebapp', '0006_alter_eventlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratetypeunit',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
    ]
