# Generated by Django 4.2.4 on 2024-03-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baaswebapp', '0007_ratetypeunit_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetypeunit',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
