# Generated by Django 4.1.2 on 2022-10-21 15:29

from django.db import migrations, models
import django.db.models.deletion
import trialapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('crop_stage_majority', models.IntegerField()),
                ('crop_stage_scale', models.CharField(max_length=10)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='ApplicationMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.application')),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='FieldTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('initiation_date', models.DateField(null=True)),
                ('completion_date', models.DateField(null=True)),
                ('farmer', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('latitude_str', models.CharField(max_length=100, null=True)),
                ('altitude', models.IntegerField(null=True)),
                ('report_filename', models.TextField(null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.crop')),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Plague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific', models.CharField(max_length=200, null=True)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='RateUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='ResultUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='TrialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('field_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.fieldtrial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.product')),
                ('rate_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.rateunit')),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
        migrations.CreateModel(
            name='ReplicaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
                ('application_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.applicationmeasurement')),
                ('replica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.replica')),
            ],
        ),
        migrations.AddField(
            model_name='replica',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.thesis'),
        ),
        migrations.CreateModel(
            name='RelatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.fieldtrial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.product')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='RawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
                ('application_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.applicationmeasurement')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.resultunit')),
            ],
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.objective'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.phase'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='plague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.plague'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.product'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.project'),
        ),
        migrations.CreateModel(
            name='ApplicationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
                ('result_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.applicationmeasurement')),
            ],
        ),
        migrations.AddField(
            model_name='applicationmeasurement',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.thesis'),
        ),
        migrations.AddField(
            model_name='applicationmeasurement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.resultunit'),
        ),
        migrations.AddField(
            model_name='application',
            name='field_trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.fieldtrial'),
        ),
    ]
