# Generated by Django 4.1.2 on 2022-10-18 14:34

from django.db import migrations, models
import trialapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, trialapp.models.ModelHelpers),
        ),
    ]
