# Generated by Django 4.1.2 on 2022-10-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replica',
            name='name',
        ),
    ]
