# Generated by Django 4.1.2 on 2022-11-17 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicadata',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.replica'),
        ),
    ]
