# Generated by Django 4.1.2 on 2022-11-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0002_alter_replicadata_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtrial',
            old_name='rows_layout',
            new_name='blocks',
        ),
        migrations.RenameField(
            model_name='fieldtrial',
            old_name='farmer',
            new_name='contact',
        ),
    ]
