# Generated by Django 4.1.2 on 2022-11-28 23:01

from django.db import migrations, models
import django.db.models.deletion
import trialapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0003_rename_rows_layout_fieldtrial_blocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('replica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.replica')),
            ],
            bases=(trialapp.models.ModelHelpers, models.Model),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.sample'),
        ),
    ]
