# Generated by Django 4.1.2 on 2022-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0004_sample_alter_sampledata_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrial',
            name='samples_per_replica',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
