# Generated by Django 4.1.2 on 2022-12-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0005_alter_fieldtrial_samples_per_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='filename',
            field=models.TextField(null=True),
        ),
    ]
