# Generated by Django 4.1.2 on 2022-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0006_fieldtrial_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='other',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
