# Generated by Django 4.1.2 on 2022-12-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0007_crop_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrial',
            name='filename',
        ),
    ]
