# Generated by Django 3.2.16 on 2022-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0012_auto_20221214_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='cro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
