# Generated by Django 3.2.16 on 2023-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0013_fieldtrial_cro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plague',
            name='other',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
