# Generated by Django 3.2.16 on 2023-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0015_remove_evaluation_crop_stage_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='comments_criteria',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='ref_to_criteria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='ref_to_eppo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
