# Generated by Django 3.2.16 on 2023-01-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0016_auto_20230113_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
