# Generated by Django 3.2.16 on 2023-02-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0021_alter_evaluation_crop_stage_majority'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='application_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
