# Generated by Django 3.2.16 on 2023-02-24 04:43

import baaswebapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0022_fieldtrial_application_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='crop_variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.cropvariety'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.applicationmode'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='cultivation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.cultivationmethod'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='irrigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.irrigation'),
        ),
    ]
