# Generated by Django 3.2.16 on 2023-02-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0023_auto_20230224_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtrial',
            name='plague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trialapp.plague'),
        ),
    ]
