# Generated by Django 3.2.16 on 2023-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0024_alter_fieldtrial_plague'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='crop_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='seed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='transplant_date',
            field=models.DateField(null=True),
        ),
    ]
