# Generated by Django 3.2.18 on 2023-02-26 23:26

import baaswebapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0025_auto_20230224_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('ddt', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('bbch', models.CharField(max_length=25)),
                ('field_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.fieldtrial')),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
    ]
