# Generated by Django 3.2.18 on 2023-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0026_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='daf',
            field=models.IntegerField(null=True),
        ),
        migrations.RenameField('application', 'ddt', 'daa'),
    ]
