# Generated by Django 3.2.18 on 2023-03-06 22:34

import baaswebapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20230219_0126'),
        ('trialapp', '0028_auto_20230228_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.thesis')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.treatment')),
            ],
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
    ]
