# Generated by Django 3.2.18 on 2023-03-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0029_treatmentthesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productthesis',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productthesis',
            name='rate_unit',
        ),
        migrations.RemoveField(
            model_name='productthesis',
            name='thesis',
        ),
        migrations.DeleteModel(
            name='ProductEvaluation',
        ),
        migrations.DeleteModel(
            name='ProductThesis',
        ),
    ]
