# Generated by Django 3.2.18 on 2023-03-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20230310_1922'),
        ('trialapp', '0030_auto_20230310_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.treatment'),
        ),
    ]
