# Generated by Django 3.2.18 on 2023-03-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0031_thesis_treatment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateUnit',
        ),
    ]
