# Generated by Django 3.2.18 on 2023-03-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0034_auto_20230325_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='field_trial',
        ),
        migrations.RemoveField(
            model_name='trialassessmentset',
            name='field_trial',
        ),
        migrations.RemoveField(
            model_name='trialassessmentset',
            name='type',
        ),
        migrations.RemoveField(
            model_name='trialassessmentset',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='replicadata',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='replicadata',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='sampledata',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='thesisdata',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='thesisdata',
            name='unit',
        ),
        migrations.DeleteModel(
            name='AssessmentType',
        ),
        migrations.DeleteModel(
            name='AssessmentUnit',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='TrialAssessmentSet',
        ),
    ]
