# Generated by Django 3.2.18 on 2023-03-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0035_auto_20230326_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicadata',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trialapp.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.assessment'),
        ),
        migrations.AlterField(
            model_name='thesisdata',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.assessment'),
        ),
    ]
