# Generated by Django 4.2.1 on 2023-06-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_delete_weather'),
        ('trialapp', '0038_fieldtrial_trial_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='application_volume_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.rateunit'),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='conclusion',
            field=models.TextField(null=True),
        ),
    ]
