# Generated by Django 4.2.1 on 2023-07-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0039_fieldtrial_application_volume_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrial',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
