# Generated by Django 4.2.1 on 2023-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0041_fieldtrial_key_ratedpart_fieldtrial_key_ratetypeunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='best_efficacy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
