# Generated by Django 4.2.1 on 2023-09-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0043_fieldtrial_key_assessment_fieldtrial_soil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldtrial',
            old_name='untreated_thesis',
            new_name='control_thesis',
        ),
    ]
