# Generated by Django 4.2.1 on 2023-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0044_rename_untreated_thesis_fieldtrial_control_thesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='avg_humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='avg_precipitation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='avg_temperature',
            field=models.IntegerField(null=True),
        ),
    ]
