# Generated by Django 4.2.1 on 2023-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0045_fieldtrial_avg_humidity_fieldtrial_avg_precipitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='favorable',
            field=models.BooleanField(default=False),
        ),
    ]
