# Generated by Django 4.2.4 on 2023-09-21 12:56

import baaswebapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_product_purpose'),
        ('trialapp', '0048_remove_fieldtrial_trial_status_delete_trialstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Plague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trialapp.plague')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'unique_together': {('product', 'plague')},
            },
            bases=(baaswebapp.models.ModelHelpers, models.Model),
        ),
    ]
