# Generated by Django 4.2.4 on 2023-09-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0049_alter_fieldtrial_soil'),
        ('trialapp', '0049_product_plague'),
    ]

    operations = [
    ]
