# Generated by Django 4.2.1 on 2023-09-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0050_merge_0049_alter_fieldtrial_soil_0049_product_plague'),
        ('trialapp', '0051_alter_fieldtrial_soil'),
    ]

    operations = [
    ]
