# Generated by Django 4.2.1 on 2023-10-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0054_alter_fieldtrial_soil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='part_rated',
            field=models.CharField(choices=[('BUNCH', 'bunch'), ('CLUSTR', 'CLUSTR'), ('FLOWER', 'FLOWER'), ('FRUIT', 'FRUIT'), ('LEAF', 'LEAF'), ('PLANT', 'PLANT'), ('PLOT', 'PLOT'), ('ROOT', 'ROOT'), ('SPOT', 'SPOT'), ('STEMP', 'STEMP'), ('UNDF', 'UNDF')], default='UNDF', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldtrial',
            name='key_ratedpart',
            field=models.CharField(choices=[('BUNCH', 'bunch'), ('CLUSTR', 'CLUSTR'), ('FLOWER', 'FLOWER'), ('FRUIT', 'FRUIT'), ('LEAF', 'LEAF'), ('PLANT', 'PLANT'), ('PLOT', 'PLOT'), ('ROOT', 'ROOT'), ('SPOT', 'SPOT'), ('STEMP', 'STEMP'), ('UNDF', 'UNDF')], default='UNDF', max_length=10),
        ),
    ]
