# Generated by Django 4.2.1 on 2023-10-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0055_alter_assessment_part_rated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrial',
            name='replicas_per_thesis',
        ),
        migrations.RenameField(
            model_name='fieldtrial',
            old_name='blocks',
            new_name='repetitions',
        ),
    ]
