# Generated by Django 4.2.4 on 2023-10-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0056_remove_fieldtrial_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtrial',
            name='comments_criteria_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='conclusion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fieldtrial',
            name='description_en',
            field=models.TextField(null=True),
        ),
    ]
