# Generated by Django 4.2.4 on 2024-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0057_fieldtrial_comments_criteria_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='part_rated',
            field=models.CharField(choices=[('BUNCH', 'bunch'), ('CLUSTR', 'CLUSTR'), ('FLOWER', 'FLOWER'), ('FRUIT', 'FRUIT'), ('LEAF', 'LEAF'), ('PLANT', 'PLANT'), ('PLOT', 'PLOT'), ('ROOT', 'ROOT'), ('SPOT', 'SPOT'), ('STEMP', 'STEMP'), ('UNDF', 'UNDF'), ('Manchas', 'Manchas'), ('Berries', 'Berries'), ('Cápsulas', 'Cápsulas'), ('Shoot', 'Shoot')], default='UNDF', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldtrial',
            name='key_ratedpart',
            field=models.CharField(choices=[('BUNCH', 'bunch'), ('CLUSTR', 'CLUSTR'), ('FLOWER', 'FLOWER'), ('FRUIT', 'FRUIT'), ('LEAF', 'LEAF'), ('PLANT', 'PLANT'), ('PLOT', 'PLOT'), ('ROOT', 'ROOT'), ('SPOT', 'SPOT'), ('STEMP', 'STEMP'), ('UNDF', 'UNDF'), ('Manchas', 'Manchas'), ('Berries', 'Berries'), ('Cápsulas', 'Cápsulas'), ('Shoot', 'Shoot')], default='UNDF', max_length=10),
        ),
    ]
