# Generated by Django 4.2.4 on 2024-03-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trialapp', '0058_assessment_unit_alter_assessment_part_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='part_rated_unit',
            field=models.CharField(choices=[('BUNCH', 'bunch'), ('CLUSTR', 'CLUSTR'), ('FLOWER', 'FLOWER'), ('FRUIT', 'FRUIT'), ('LEAF', 'LEAF'), ('PLANT', 'PLANT'), ('PLOT', 'PLOT'), ('ROOT', 'ROOT'), ('SPOT', 'SPOT'), ('STEMP', 'STEMP'), ('UNDF', 'UNDF'), ('Manchas', 'Manchas'), ('Berries', 'Berries'), ('Cápsulas', 'Cápsulas'), ('Shoot', 'Shoot')], default='UNDF', max_length=10),
        ),
    ]
